// @ts-check

// Define DevopsSidebar separately
const DevopsSidebar = [
  {
    type: 'category',
    label: 'DevOps',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'CMake',
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'knowhow/devops/cmake/intro',
            label: 'Endpoints',
          },
        ],
      },
      // {
      //   type: 'category',
      //   label: 'Docker',
      //   collapsed: true,
      //   items: [
      //     {
      //       type: 'doc',
      //       id: 'knowhow/devops/docker/intro', // ⚡ fixed id
      //       label: 'Endpoints',
      //     },
      //   ],
      // },
    ],
  },
];

// Define FpgaSidebar separately
const FpgaSidebar = [
  {
    type: 'category',
    label: 'Fpga',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'tang fpga',
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'knowhow/fpga/intro',
            label: 'Endpoints',
          },
        ],
      },
      // {
      //   type: 'category',
      //   label: 'Docker',
      //   collapsed: true,
      //   items: [
      //     {
      //       type: 'doc',
      //       id: 'knowhow/devops/docker/intro', // ⚡ fixed id
      //       label: 'Endpoints',
      //     },
      //   ],
      // },
    ],
  },
];

// Define FpgaSidebar separately
const LanguagesSidebar = [
  {
    type: 'category',
    label: 'Coding',
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'C-CPP',
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'knowhow/programming-languages/c-cpp/intro',
            label: 'Endpoints',
          },
          // 'knowhow/programming-languages/c-cpp/autogen',        
        ],
      },
      {
        type: 'category',
        label: 'Golang',
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'knowhow/programming-languages/golang/intro',
            label: 'Endpoints',
          },
        ],
      },
      // - knowhow/programming-languages/lua/intro
      // - knowhow/programming-languages/python/intro

    ],
  },
];


// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)


/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  DevopsSidebar,
  FpgaSidebar,
  LanguagesSidebar,

   DocsySidebar: [
    {
      // programming-languages
      type: 'category',
      label: 'Getting Started',
      className: 'category-cms-getting-started',
      collapsible: false,
      items: [
        'knowhow/example/intro',        
        ...DevopsSidebar,
        ...FpgaSidebar,
        ...LanguagesSidebar,
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: false,
      collapsible: false,
      className: 'category-cms-typescript', // TODO: add CSS for icon
      items: [
        {
          type: 'html',
          value: 'placeholder', // a value is required for the HTML type, but it is not rendered
          customProps: {
            tooltipTitle: 'This section is new',
            tooltipContent:
              'I grouped all the Security-related content into a new section, including configurations, development tips, and guides.',
          },
        },
        {
          type: 'doc',
          id: 'knowhow/example/intro',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'knowhow/example/intro',
          label: 'Configuration',
        },
        {
          type: 'doc',
          id: 'knowhow/example/intro',
          label: 'Development',
        },
        {
          type: 'doc',
          id: 'knowhow/example/intro',
          label: 'Guides', // TODO ensure label is overriden
        },
        // 'cms/typescript/adding-support-to-existing-project' // ? will be linked from the Guides page
      ],
    },
    {
      type: 'category',
      collapsed: true,
      collapsible: true,
      label: 'Database',
      // className: 'category-cms-typescript', // TODO: add CSS for icon
      customProps: {
          tooltip:
          'This section now regroups all the database-related configurations and guides, including migrations and transactions.',
      },
      items: [
        {
          type: 'doc',
          id: 'knowhow/example/intro',
          label: 'Database configuration',
        },
        'knowhow/example/intro',
        'knowhow/example/intro',
        {
          type: 'link',
          label: 'Introduction',
          href: 'knowhow/example/intro',//redirect with href
        },
        {
          type: 'doc',
          id: 'knowhow/example/intro', //redirect with id
          customProps: {
            updated: false,
            tooltip: `<strong>Important changes</strong><br/><br/>
            <span>This tooltip can be used to display short pieces of information.</span><br><br>
            We may use bullets in the tooltip as well:<br>
            <ul>
              <li>This item is purely informative</li>
              <li>Please avoid using links here as those tooltips are not hoverable</li>
            </ul><br/>`
          },
        },
      ],
    },
  ],
  
};

export default sidebars;
